// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltantdmbkumnicnszzci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0YW50ZG1ia3VtbmljbnN6emNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NTgzODksImV4cCI6MjA1OTAzNDM4OX0.fCQmDbN1gHgTKY08HRiC5XSyyIZQyfiZnKjZwWwqNQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);